name: KitShop
version: 1.1.1
main: KitShop\Main
api: 5.0.0
softdepend:
  - BedrockEconomy
commands:
  kit:
    description: Opens the kit shop GUI
    usage: "/kit"
    permission: kitshop.command.kit
permissions:
  kitshop.command.kit:
    description: Allows access to the /kit command
    default: true