name: KitShop
version: 1.0.1
api: 5.0.0
main: KitShop\Main
description: A plugin for managing kits and a shop GUI.
author: YourName
commands:
  kitshop:
    description: Opens the KitShop GUI.
    usage: /kitshop
permissions:
  kitshop.use:
    default: true
    description: Allows the player to use /kitshop